name: Prueba de Acción

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Ejecutar Prueba
      run: python ConsumirSecretGitHub/consumo_secret.py
      env:
        GS_SECRET_MESSAGE: ${{ secrets.GS_SECRET_MESSAGE }}