name: Prueba de Acción

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2  # Asegúrate de usar la última versión compatible con Node.js 16

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Puedes ajustar la versión de Python según tus necesidades

    - name: Ejecutar Prueba
      run: python hola_mundo.py
      env:
        GS_SECRET_MESSAGE: ${{ secrets.GS_SECRET_MESSAGE }}